hands

diff --git a/add_word b/add_word
--- a/add_word
+++ b/add_word
@@ -2,8 +2,8 @@
 
 word_file=$(mktemp new_word.XXXX)
 epoch=$(date '+%s')
-tomorrow=$(($epoch + 1))
-#tomorrow=$(date -d 'tomorrow' '+%s')
+tomorrow=$(($epoch + 86400))
+
 cat << EOF > $word_file
 ----------------------------------------
 id: $epoch
@@ -11,7 +11,20 @@ foreign:
 english:
 notes:
 EOF
-vim $word_file
+
+vim $word_file -c "normal jj$"
+
+if ! egrep -q 'english: ?\w' $word_file
+then
+    echo "Aborting due to badly formatted english" && exit 1
+fi
+
+if ! egrep -q 'foreign: ?\w' $word_file
+then
+    echo "Aborting due to badly formatted foreign" && exit 1
+fi
+
+
 cat $word_file >> words
 rm $word_file
 cat << EOF >> due_dates
